### ISSUE TITLE
query_string added to planner hook in pg13

### ISSUE THREAD

**Issue by legrandlegrand** [AmatanHead/psql-hooks#3]
Hello,
thank you for this helpfull work !

for information, planner hook has changed in pg13:
https://www.postgresql-archive.org/pgsql-Allow-the-planner-related-functions-and-hook-to-accept-the-query-td6129676.html

 PlannedStmt *
-planner(Query *parse, int cursorOptions, ParamListInfo boundParams)
+planner(Query *parse, const char *query_string, int cursorOptions, ParamListInfo boundParams)

Regards
PAscal

**Comment by AmatanHead** [comment]
Hi!

Thanks for pointing this out, I've updated the function signature.

The truth is, this documentation is not actively maintained, so there's probably more outdated stuff =( I think I have to merge this somehow into the official PG documentation, as suggested by #2, otherwise this documentation may become misleading. I'll see what I can do.
