### ISSUE TITLE
SPI_execute failing in ClientAuthentication_hook

### ISSUE THREAD

**Issue by markhooper99** [AmatanHead/psql-hooks#5]
I'm trying to build an equivalent of a 'logon trigger' in EDB Postgres AS12 - I need a procedure to be run which will set a session level variable in the database session that has just connected.  I'm trying to use the ClientAuthentication_hook to make it so.

My idea is to use SPI_connect , SPI_execute and SPI_finish to make this work - I've built a very simplistic bit of code that proves that the hook 'plumbing' works - it is attached (I'm very rusty when it comes to C and this is just a test mule).  Note, I had to put a .txt extension on it to get it to attach.

[my_client_auth.c.txt](https://github.com/AmatanHead/psql-hooks/files/5691463/my_client_auth.c.txt)

The SPI_connect returns a code of 1 but when SPI_execute runs I get an error in the log ...

```
2020-12-14 14:29:05 CST WARNING:  kdm_us_view
2020-12-14 14:29:05 CST WARNING:  HOOK - kdm_us_view user logged in
2020-12-14 14:29:05 CST WARNING:  _PG_init() - MyProcPid=71042, MyDatabaseId=0, IsBackgroundWorker=0, isExecutingLogin=0
2020-12-14 14:29:05 CST WARNING:  back from SPI_connect 1
**2020-12-14 14:29:05 CST FATAL:  cannot read pg_class without having selected a database**
2020-12-14 14:29:05 CST CONTEXT:  SQL statement "select dmass38.iglass_test"
```

I cannot figure out why I'm getting this error - any tips would be appreciated, thanks.

**Comment by AmatanHead** [comment]
Hi @markhooper99,

I'm not sure I can be of much help, because this is not an official postgres documentation, and I haven't worked with postgres hooks for quite some time. My intuition would be that the connection is not yet initialised when the auth hook is executed. I may be wrong, however. Perhaps you can try one of [official mailing lists](https://www.postgresql.org/list/)? Maybe [this thread](https://www.postgresql.org/message-id/4EDAA3B0.1010707@fuzzy.cz) could be helpful?

**Comment by markhooper99** [comment]
Thx @AmatanHead I will check it out.
